<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-13T22:30:49 IST" name="TestSuite" finished-at="2023-07-13T22:30:49 IST" duration-ms="224">
    <groups>
    </groups>
    <test started-at="2023-07-13T22:30:49 IST" name="CreateAccount" finished-at="2023-07-13T22:30:49 IST" duration-ms="224">
      <class name="com.share.testcase.CreateAccount">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.share.testcase.CreateAccount@293bb8a5]" started-at="2023-07-13T22:30:43 IST" name="setUp" finished-at="2023-07-13T22:30:49 IST" duration-ms="6328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="createAccount()[pri:0, instance:com.share.testcase.CreateAccount@293bb8a5]" started-at="2023-07-13T22:30:49 IST" name="createAccount" finished-at="2023-07-13T22:30:49 IST" duration-ms="15" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test CREATEACCOUNT as th Run mode is no]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test CREATEACCOUNT as th Run mode is no
at com.share.listeners.CustomListeners.onTestStart(CustomListeners.java:24)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:106)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:277)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:638)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccount -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.share.testcase.CreateAccount@293bb8a5]" started-at="2023-07-13T22:30:49 IST" name="tearDown" finished-at="2023-07-13T22:30:49 IST" duration-ms="116" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.share.testcase.CreateAccount -->
    </test> <!-- CreateAccount -->
  </suite> <!-- TestSuite -->
</testng-results>
